export const CONFIG = {
  appName: 'Headhunt.cc',
  appShortName: 'Headhunt',
  buildId: process.env.NEXT_PUBLIC_BUILD_ID ?? 'development',
  repositoryUrl: 'https://github.com/baguspangestu/headhunt',
  baseUrl:
    process.env.NODE_ENV === 'production'
      ? 'https://headhunt.cc'
      : 'http://localhost:3000',
  discordUrl: 'https://discord.gg/jBNxtSstEa',
  googleClientId: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID ?? '',
  locales: [
    {
      id: 'cn',
      value: 'zh-cn',
      region: 'zh_Hans',
      enable: false,
      name: '简体中文',
    },
    {
      id: 'tw',
      value: 'zh-tw',
      region: 'zh_Hant',
      enable: false,
      name: '繁體中文',
    },
    {
      id: 'de',
      value: 'de-de',
      region: 'de_DE',
      enable: false,
      name: 'Deutsch',
    },
    {
      id: 'en',
      value: 'en-us',
      region: 'en',
      enable: true,
      name: 'English',
    },
    {
      id: 'es',
      value: 'es-mx',
      region: 'es_MX',
      enable: false,
      name: 'Español',
    },
    {
      id: 'fr',
      value: 'fr-fr',
      region: 'fr_FR',
      enable: false,
      name: 'Français',
    },
    {
      id: 'id',
      value: 'id-id',
      region: 'id_ID',
      enable: true,
      name: 'Indonesia',
    },
    {
      id: 'it',
      value: 'it-it',
      region: 'it_IT',
      enable: false,
      name: 'Italiano',
    },
    {
      id: 'ja',
      value: 'ja-jp',
      region: 'ja',
      enable: false,
      name: '日本語',
    },
    {
      id: 'ko',
      value: 'ko-kr',
      region: 'ko',
      enable: false,
      name: '한국어',
    },
    {
      id: 'pt',
      value: 'pt-br',
      region: 'pt_BR',
      enable: false,
      name: 'Português',
    },
    {
      id: 'ru',
      value: 'ru-ru',
      region: 'ru_RU',
      enable: false,
      name: 'Pусский',
    },
    {
      id: 'th',
      value: 'th-th',
      region: 'th_TH',
      enable: false,
      name: 'ภาษาไทย',
    },
    {
      id: 'vi',
      value: 'vi-vn',
      region: 'vi_VN',
      enable: false,
      name: 'Tiếng Việt',
    },
  ],
  guaranteedLimit: {
    operator: 120,
    weapon: 80,
  },
  enumColors: {
    rarities: {
      rarity_3: '#33C2FF',
      rarity_4: '#B380FF',
      rarity_5: '#FFCC00',
      rarity_6: '#FF7100',
    },
    elements: {
      char_property_fire: '#FF623D',
      char_property_pulse: '#FFC000',
      char_property_cryst: '#21C6D0',
      char_property_natural: '#9EDC23',
      char_property_physical: '#888888',
    },
    opClass: {
      profession_guard: '#444444',
      profession_caster: '#444444',
      profession_assault: '#444444',
      profession_vanguard: '#444444',
      profession_defender: '#444444',
      profession_supporter: '#444444',
    },
    wpTypes: {
      weapon_type_sword: '#444444',
      weapon_type_claymores: '#444444',
      weapon_type_pistol: '#444444',
      weapon_type_wand: '#444444',
      weapon_type_lance: '#444444',
    },
  },
  contentColors: {
    light_text_black: 'rgba(0,0,0,1)',
    light_text_primary: '#FFFFFF',
    light_text_secondary: 'rgba(94,94,94,1)',
    light_text_tertiary: 'rgba(120,120,120,1)',
    light_text_quaternary: 'rgba(167,167,167,1)',
    light_rank_gray: 'rgba(140,140,140,1)',
    light_rank_green: 'rgba(109,154,0,1)',
    light_rank_blue: 'rgba(29,166,224,1)',
    light_rank_purple: 'rgba(153,89,255,1)',
    light_rank_yellow: 'rgba(204,153,0,1)',
    light_rank_orange: 'rgba(229,103,0,1)',
    light_function_orange: 'rgba(244,85,17,1)',
    light_function_turquoise: 'rgba(0,156,173,1)',
    light_function_green: 'rgba(109,154,0,1)',
    light_function_sandstone: 'rgba(166,131,96,1)',
    light_function_yellow: 'rgba(204,153,0,1)',
    light_function_red: 'rgba(229,69,69,1)',
    light_function_blue: 'rgba(29,166,224,1)',
    light_function_brown: 'rgba(187, 106, 38, 1)',
    light_function_violet: 'rgba(153, 89, 255, 1)',
    light_function_blueness: 'rgba(253,199,0,1)',
  },
} as const;
